version: "3.8"
services:
  spark:
    image: bitnami/spark:latest
    container_name: spark
    ports:
      - "4040:4040"
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: biofuel_user
      POSTGRES_PASSWORD: biofuel_pass
      POSTGRES_DB: biofuel_db
    ports:
      - "5432:5432"
